import React, { useRef } from "react";
import ReactDOM from "react-dom";

export const Modal = ({
  setShowModal,
  clientClickPosition,
  allPositions,
  lastFound,
  previouslyFound,
  setPreviouslyFound,
}) => {
  const useModalRef = useRef();
  const closeModal = (e) => {
    if (e.target === useModalRef.current) {
      setShowModal(false);
    }
  };

  const screenWidth = window.innerWidth;
  const screenHeight = window.innerHeight;
  const isOverflowingScreen = screenWidth * 0.52 < clientClickPosition.x;
  const isOverflowingScreenY = screenHeight * 0.71 < clientClickPosition.y;
  const avoidOverflow = clientClickPosition.x * 0.5;
  const avoidOverflowY = clientClickPosition.y * 0.75;

  const modalLocation = {
    left: isOverflowingScreen
      ? avoidOverflow + "px"
      : clientClickPosition.x + "px",
    top: isOverflowingScreenY ? avoidOverflowY : clientClickPosition.y + "px",
  };

  const validateFind = (e) => {
    // Yes! We're getting the name of the person from the "alt" attr
    const personFound = e.target.alt;
    if (lastFound !== personFound) {
      return;
    } else if (previouslyFound.includes(personFound)) {
      return;
    }
    setPreviouslyFound((prevFound) => [...prevFound, personFound]);
    const toStyle = document.querySelector(`[data-person-name=${personFound}]`);
    toStyle.classList.add("grayed");
    // Here, we could fire up a new modal:
    // You found {personFound}!
    // <a cool image of the person>
    // if it's Ramona: 'What took you so long?', if it's Rogue: 'Nice goin', Sugah!', if it's Deadpool: 'Yeah yeah thanks I guess'
    // console.log(personFound);
    // console.log(previouslyFound);
  };

  console.log("previouslyFound: ");
  console.log(previouslyFound);
  //   Renders modal to the portal in index.html

  // map
  // we could store the data locally
  const thumbnails = allPositions.map((person) => {
    return (
      // for each key={}, use the id generated by firebase.
      <div className="person-preview" key={person.id}>
        <img
          src={person.thumbnail}
          alt={person.name}
          data-person-name={person.name}
          className="thumbnail"
          onClick={validateFind}
        />
        <span>{person.name}</span>
      </div>
    );
  });

  return ReactDOM.createPortal(
    <div className="modal-container" ref={useModalRef} onClick={closeModal}>
      <div className="modal" style={modalLocation}>
        {/* Who's that?
            map over each individual in allPositions and display their image, like:
            <img src={person.thumbnail} alt={person.name}/>  
        */}
        <h4>Who's that?</h4>
        <div className="thumbnails-div">{thumbnails}</div>
        <button onClick={() => setShowModal(false)}>X</button>
      </div>
    </div>,
    document.getElementById("portal")
  );
};
